import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import InstantEstimateCTA from "@/components/layout/InstantEstimateCTA";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://charlotteroofinghub.com'),
  title: {
    default: "Charlotte Roofing Hub | Find Top-Rated Roofers in Charlotte NC",
    template: "%s | Charlotte Roofing Hub"
  },
  description: "Charlotte Roofing Hub is a free site offering Charlotte homeowners roofing information, materials and pricing guides, and a curated list of suggested local roofing companies. We don't sell leads. Many of the listed companies contribute content to the site.",
  keywords: [
    // Primary Charlotte Keywords
    "roofing companies charlotte nc",
    "charlotte roofing contractors",
    "best roofers in charlotte",
    "roof repair charlotte",
    "new roof charlotte nc",
    "roof replacement charlotte",
    // Service Keywords
    "residential roofing charlotte",
    "commercial roofing charlotte",
    "metal roofing charlotte nc",
    "shingle roof replacement charlotte",
    "roof estimate charlotte",
    "charlotte roof installation",
    "roof contractors near me",
    "affordable roofing charlotte",
    "emergency roof repair charlotte",
    "storm damage roof repair charlotte nc",
    "roof inspection charlotte",
    // Surrounding Areas (GEO)
    "roofing contractors matthews nc",
    "huntersville roofing companies",
    "concord nc roofers",
    "mooresville roofing contractors",
    "mint hill roof repair",
    "indian trail roofing",
    "waxhaw roofing companies",
    "fort mill roofing contractors",
    "gastonia roofers",
    "cornelius roof replacement",
    // Long-tail Keywords (AEO)
    "best rated roofers charlotte nc",
    "how much does a roof cost in charlotte",
    "free roof estimate charlotte nc",
    "veteran owned roofing company charlotte",
    "BBB accredited roofers charlotte",
    "GAF master elite roofer charlotte",
    "owens corning preferred contractor charlotte"
  ],
  authors: [{ name: "Charlotte Roofing Hub" }],
  creator: "Charlotte Roofing Hub",
  publisher: "Charlotte Roofing Hub",
  formatDetection: {
    email: true,
    address: true,
    telephone: true,
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://charlotteroofinghub.com",
    siteName: "Charlotte Roofing Hub",
    title: "Charlotte Roofing Hub | Free Charlotte Roofing Information & Local Companies",
    description: "Free Charlotte roofing information, materials and pricing guides, and a curated list of suggested local roofing companies. We don't sell leads.",
    // og:image is auto-generated by src/app/opengraph-image.tsx (Next file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: "Charlotte Roofing Hub | Free Charlotte Roofing Information & Local Companies",
    description: "Free Charlotte roofing information and a curated list of suggested local roofing companies. We don't sell leads.",
    // twitter:image inherits the opengraph-image route automatically.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://charlotteroofinghub.com",
  },
  // verification.google: add real Search Console TXT/HTML token here once verified.
  // Leaving the placeholder in place outputs a meta tag with a bogus value.
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#1e3a5f",
};

// Structured Data for the website
function WebsiteSchema() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Charlotte Roofing Hub",
    url: "https://charlotteroofinghub.com",
    description: "Your trusted source for finding quality roofing companies in Charlotte, NC",
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: "https://charlotteroofinghub.com/companies?search={search_term_string}"
      },
      "query-input": "required name=search_term_string"
    }
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

function OrganizationSchema() {
  // Generic Organization type. Site is a free resource — it does not sell
  // leads — but it is not registered as a 501(c)(3), so do NOT use NGO /
  // nonprofitStatus markup. logo points at the auto-generated /apple-icon
  // PNG until a higher-resolution brand logo is uploaded (Schema.org
  // recommends a square logo of at least 112×112 px).
  const schema = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": "https://charlotteroofinghub.com/#organization",
    name: "Charlotte Roofing Hub",
    url: "https://charlotteroofinghub.com",
    logo: "https://charlotteroofinghub.com/apple-icon",
    description: "A free Charlotte roofing information site. We don't sell leads. We publish roofing guides and maintain a curated list of suggested local roofing companies — many of which contribute content to the site.",
    slogan: "Free Charlotte roofing information. No lead selling.",
    areaServed: {
      "@type": "City",
      name: "Charlotte",
      containedInPlace: {
        "@type": "State",
        name: "North Carolina"
      }
    },
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer service",
      email: "info@charlotteroofinghub.com",
      areaServed: "US-NC",
      availableLanguage: "English"
    },
    knowsAbout: [
      "Charlotte roofing companies",
      "Roofing materials and pricing",
      "Residential roofing",
      "Commercial roofing",
      "Storm damage and insurance claims"
    ],
    inLanguage: "en-US"
    // sameAs: [...] // Add social profile URLs once accounts are live
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

// LocalBusinessAggregateSchema removed: it was a one-item placeholder
// ItemList rendered on every page. The canonical /companies route emits
// a complete ItemList of every RoofingContractor (CompanyListSchema in
// src/app/companies/page.tsx) with real data. Repeating a stub globally
// dilutes the real listing schema.

// AEO/GEO Optimized - Professional Service Schema
// Linked to OrganizationSchema via @id so search engines treat them as
// the same entity rather than two competing brand records.
function ProfessionalServiceSchema() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    "@id": "https://charlotteroofinghub.com/#organization",
    name: "Charlotte Roofing Hub",
    url: "https://charlotteroofinghub.com",
    description: "A free Charlotte roofing information site with a curated list of suggested local roofing companies — many of whom contribute content to the site. We don't sell leads.",
    serviceType: "Verified Roofing Contractor Directory",
    slogan: "Locally Verified. Background Checked. Trusted by Charlotte.",
    areaServed: [
      {
        "@type": "City",
        name: "Charlotte",
        containedInPlace: { "@type": "State", name: "North Carolina", "@id": "https://www.wikidata.org/wiki/Q1454" }
      },
      { "@type": "City", name: "Matthews", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Huntersville", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Concord", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Cornelius", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Davidson", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Mooresville", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Mint Hill", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Indian Trail", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Waxhaw", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Fort Mill", containedInPlace: { "@type": "State", name: "South Carolina" } },
      { "@type": "City", name: "Rock Hill", containedInPlace: { "@type": "State", name: "South Carolina" } },
      { "@type": "City", name: "Gastonia", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Kannapolis", containedInPlace: { "@type": "State", name: "North Carolina" } },
      { "@type": "City", name: "Pineville", containedInPlace: { "@type": "State", name: "North Carolina" } }
    ],
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "Roofing Services Directory",
      itemListElement: [
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Residential Roofing" } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Commercial Roofing" } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Roof Repair" } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Roof Replacement" } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Storm Damage Repair" } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Emergency Roofing" } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Roof Inspection" } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Gutter Installation" } }
      ]
    }
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

// AEO Optimized - FAQ Schema for Voice Search & AI Assistants
function GlobalFAQSchema() {
  const schema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "How does Charlotte Roofing Hub verify roofing companies?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Charlotte Roofing Hub personally verifies every suggested roofing company through a rigorous process: 1) We meet face-to-face with company owners, 2) We conduct thorough background checks, 3) We verify licensing, insurance, and certifications, 4) We confirm 4.8+ star Google ratings. Many of the listed companies also contribute content to the site."
        }
      },
      {
        "@type": "Question",
        name: "Is Charlotte Roofing Hub free to use?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes — Charlotte Roofing Hub is 100% free for homeowners. We don't sell leads. The site offers free roofing information, materials and pricing guides, and a curated list of suggested local roofing companies. Many of those companies contribute content to the site."
        }
      },
      {
        "@type": "Question",
        name: "What is the best roofing company in Charlotte NC?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Based on our personal verification and background checks, Charlotte has many excellent roofing companies. All 25+ companies listed on Charlotte Roofing Hub have been personally vetted - we meet owners face-to-face, run background checks, and only list companies with 4.8+ star Google ratings. Browse our directory to compare verified contractors."
        }
      },
      {
        "@type": "Question",
        name: "How much does a new roof cost in Charlotte NC?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "In Charlotte NC, a new roof typically costs between $8,000 and $25,000 for residential homes, depending on size, materials, and complexity. Asphalt shingles average $4-7 per square foot installed, metal roofing $8-14, and premium materials like slate can exceed $20 per square foot. Get a free instant estimate at CharlotteRoofingHub.com."
        }
      },
      {
        "@type": "Question",
        name: "How do I find a reputable roofer in Charlotte?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "To find a reputable roofer in Charlotte: 1) Check Google reviews (look for 4.8+ stars), 2) Verify BBB accreditation, 3) Confirm proper licensing and insurance, 4) Look for manufacturer certifications (GAF Master Elite, Owens Corning Platinum), 5) Get multiple estimates. Charlotte Roofing Hub lists only verified contractors with 4.8+ star ratings."
        }
      },
      {
        "@type": "Question",
        name: "What roofing materials are best for Charlotte NC weather?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "For Charlotte's humid subtropical climate with hot summers and occasional storms, the best roofing materials are: Architectural asphalt shingles (most popular, 25-30 year warranty), Metal roofing (excellent durability, energy efficient), and Impact-resistant shingles for hail protection. Avoid materials that don't handle humidity well."
        }
      },
      {
        "@type": "Question",
        name: "Does homeowners insurance cover roof replacement in NC?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "In North Carolina, homeowners insurance typically covers roof damage from sudden events like storms, hail, fallen trees, and fire. It generally does not cover normal wear and aging. Many Charlotte roofers like Horizon Roofing, Merritt Roofing, and Regal Roofing specialize in insurance claim assistance and can help navigate the process."
        }
      },
      {
        "@type": "Question",
        name: "How long does a roof replacement take in Charlotte?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "A typical residential roof replacement in Charlotte takes 1-3 days for asphalt shingles, depending on roof size and weather. Larger homes or complex roofs may take 3-5 days. Metal roofing installations typically require 2-4 days. Most Charlotte roofing companies offer same-week scheduling for urgent needs."
        }
      }
    ]
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  );
}

// SpeakableSchema removed: the CSS-selector approach pointed at
// ".hero-description" and ".faq-answer", but page-level lead paragraphs
// already use the more current data-speakable="true" attribute. Its
// mainEntity ItemList was also a placeholder duplicating content already
// emitted by the canonical /companies CompanyListSchema.

// LocalBusiness schema intentionally omitted at the global level:
// - No real public phone (placeholder +1-704-555-ROOF previously used)
// - No storefront / single physical location
// - The previous aggregateRating (4.9 / 25 reviews) actually belonged to
//   listed contractors — applying it to the directory itself violates
//   Google's structured-data guidelines on rating manipulation.
// Each RoofingContractor on /companies/[slug] carries its own legitimate
// aggregateRating; that's the correct place for ratings.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Core Schema Markup */}
        <WebsiteSchema />
        <OrganizationSchema />

        {/* AEO/GEO Optimized Schema for AI & Voice Search */}
        <ProfessionalServiceSchema />
        <GlobalFAQSchema />

        {/* Favicons are auto-generated by Next file conventions:
            src/app/icon.tsx (32×32) and src/app/apple-icon.tsx (180×180).
            The src/app/favicon.ico is the legacy fallback. theme-color is
            set via the viewport export above. */}

        {/* Geographic Targeting for Local SEO */}
        <meta name="geo.region" content="US-NC" />
        <meta name="geo.placename" content="Charlotte" />
        <meta name="geo.position" content="35.2271;-80.8431" />
        <meta name="ICBM" content="35.2271, -80.8431" />

        {/* Robot directives are emitted by the metadata.robots object above —
            don't duplicate them here. Bingbot doesn't honor a separate
            <meta name="bingbot"> the way Googlebot does, so the standard
            "robots" tag (set via metadata.robots) is enough. */}

        {/* Mobile Optimization — viewport set via Next.js metadata API.
            maximum-scale=5 removed: blocking pinch-zoom is a WCAG 1.4.4
            accessibility violation. */}
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />

        {/* Preconnect for Performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />

        {/* DNS Prefetch for External Resources */}
        <link rel="dns-prefetch" href="https://www.google-analytics.com" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Header />
        <main className="flex-grow">
          {children}
        </main>
        <Footer />
        <InstantEstimateCTA variant="popup" />
      </body>
    </html>
  );
}
